apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: dns-gateway
spec:
  project: default
  sources:
    - repoURL: oci://codeberg.org/k8s-gateway/charts/k8s-gateway
      path: .
      targetRevision: 3.7.3
      helm:
        valueFiles:
          - $values/k8s/manifests/k8s_gateway/values.yaml
    - repoURL: https://github.com/dancavallaro/rpi-config
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dns-gateway
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
