authentik:
  secret_key: "REDACTED"
  postgresql:
    password: "REDACTED"
  error_reporting:
    enabled: false
server:
  ingress:
    ingressClassName: cilium
    enabled: true
    hosts:
      - authentik.o.cavnet.cloud
postgresql:
  enabled: true
  auth:
    password: "REDACTED"
redis:
  enabled: true
server:
  ingress:
    tls:
      - hosts:
        - authentik.o.cavnet.cloud
