# TODO: turn down logging level, it's way too verbose (on the server at least)
authentik:
  # TODO: exposing these doesn't really matter but i should probably rotate them and get them out of github anyway.
  secret_key: "REDACTED"
  postgresql:
    password: "REDACTED"
  error_reporting:
    enabled: false
server:
  ingress:
    ingressClassName: cilium
    enabled: true
    hosts:
      - authentik.o.cavnet.cloud
    tls:
      - hosts:
          - authentik.o.cavnet.cloud
postgresql:
  enabled: true
  auth:
    password: "REDACTED"
redis:
  enabled: true
