[all]
rpi.lan arch=arm64 monitor_ups=true enable_spiffe=true
bastion.lan arch=arm64 enable_spiffe=true
talos-host.lan arch=amd64
protectli.lan arch=amd64 enable_console=true docker_ip_forward_no_drop=true

[proxmox]
dpu-host.lan
