apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  namespace: matter
  name: home
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "home",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp9s0",
          "mode": "bridge",
          "mac": "02:d7:c0:00:0c:02",
          "ipam": {
            "type": "static",
            "addresses": [{ "address": "192.168.6.102/22" }]
          }
        },
        {
          "type": "tuning",
          "sysctl": {
            "net.ipv6.conf.net1.accept_ra": "2",
            "net.ipv6.conf.net1.accept_ra_rt_info_max_plen": "64"
          }
        }
      ]
    }
